//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSR_Contigent
    {
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryNameShort { get; set; }
        public string ISOCode2 { get; set; }
        public string ISOCode3 { get; set; }
        public string FlagImageFilePath { get; set; }
        public string IconFilePath { get; set; }
        public string SmallIconFilePath { get; set; }
        public Nullable<int> RegionID { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int ModifiedBy { get; set; }
    }
}
